import React from "react";
import { ThemeProvider } from "./Context/ThemeContext";

export const metadata = {
  title: '@Arthur.vsl',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
