import type { Metadata } from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "@Arthur.vsl",
  description: "Arthur.vsl / Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        {children}
      </body>
    </html>
  );
}
